export const path = {
  homePage: "/",
  productPage: "/product",
  productDetailPage: "/product/detail",
  managerUserPage: "manager-user",
  managerProductPage: "manager-product",
  
  signUp: "/sign-up",
  logIn: "/log-in",
  user:"/user",
  admin: "/admin",
  //   dashboard: "dashboard",
  //   managerUser: "manager-user",
  //   managerCategory: "manager-category",
  //   myCourse: "my-courses",
  //   blog: "blog",
  //   contact: "contact",
    myAccount: "my-account",
  //   myLearning: "my-learning",
  //   coursesDetail: "courses-detail/:courseId",
  //   managerCourse: "manager-course",
  //   cart: "cart",
  //   search: "search",
};
