export const path = {
  homePage: "/",
  productPage: "/product",
  productDetailPage: "/product-detail/:id_product",
  categoryPage: "/category/:id_category",
  managerUserPage: "manager-user",
  managerProductPage: "manager-product",
  managerCategoryPage: "manager-category",
  managerOrderPage: "manager-order",
  managerGalleryPage: "manager-gallery",
  signUp: "/sign-up",
  showRoom: "/showroom",
  oderPage: "/cart",
  logIn: "/log-in",
  user: "/user",
  admin: "/admin",
  cartPage: "/oder",
  orderAllPage: "order-all",
  orderConfirmedPage: "order-confirmed",
  orderPendingPage: "order-pending",
  orderCancelledPage: "order-cancelled",
  orderDeliveringPage: "order-delivering",
  orderDeliveredPage: "order-delivered",
  orderFailedPage: "order-failed",

  //   dashboard: "dashboard",
  //   managerUser: "manager-user",
  //   managerCategory: "manager-category",
  //   myCourse: "my-courses",
  //   blog: "blog",
  //   contact: "contact",
  myAccount: "my-account",
  //   myLearning: "my-learning",
  //   coursesDetail: "courses-detail/:courseId",
  //   managerCourse: "manager-course",
  //   cart: "cart",
  //   search: "search",
};
